# Generated by Django 2.2.8 on 2022-04-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualIVR', '0003_auto_20220412_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content_path',
            field=models.CharField(max_length=200),
        ),
    ]
